// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trobudpilsripjijlnvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyb2J1ZHBpbHNyaXBqaWpsbnZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MzA2MjgsImV4cCI6MjA1NzUwNjYyOH0.0uf7fFPQKRHHiu7gi-TPZebeNH6uUDjjwcRCnhg5nW4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);